//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment(User user, Image image, string text)
        {
            this.text = text;
            Image = image;
            User = user;
        }

        public int commentId { get; set; }
        public string text { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual User User { get; set; }
    }
}
