//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Comments = new HashSet<Comment>();
            this.UserLikes = new HashSet<User>();
        }
    
        public long imageId { get; set; }
        public int likes { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string aperture { get; set; }
        public string balance { get; set; }
        public string exposure { get; set; }
        public long usrId { get; set; }
        public long categoryId { get; set; }
        public string imagePath { get; set; }
        public System.DateTime creationDate { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ImageComment
        /// </summary>
        public virtual ICollection<Comment> Comments { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_UserPost
        /// </summary>
        public virtual User User { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): Like
        /// </summary>
        public virtual ICollection<User> UserLikes { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_ImageCategory
        /// </summary>
        public virtual Category Category { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + likes.GetHashCode();
    			hash = hash * multiplier + (title == null ? 0 : title.GetHashCode());
    			hash = hash * multiplier + (description == null ? 0 : description.GetHashCode());
    			hash = hash * multiplier + (aperture == null ? 0 : aperture.GetHashCode());
    			hash = hash * multiplier + (balance == null ? 0 : balance.GetHashCode());
    			hash = hash * multiplier + (exposure == null ? 0 : exposure.GetHashCode());
    			hash = hash * multiplier + usrId.GetHashCode();
    			hash = hash * multiplier + categoryId.GetHashCode();
    			hash = hash * multiplier + (imagePath == null ? 0 : imagePath.GetHashCode());
    			hash = hash * multiplier + creationDate.GetHashCode();
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type? 
    
            Image target = obj as Image;
    
    		return true
               &&  (this.imageId == target.imageId )       
               &&  (this.likes == target.likes )       
               &&  (this.title == target.title )       
               &&  (this.description == target.description )       
               &&  (this.aperture == target.aperture )       
               &&  (this.balance == target.balance )       
               &&  (this.exposure == target.exposure )       
               &&  (this.usrId == target.usrId )       
               &&  (this.categoryId == target.categoryId )       
               &&  (this.imagePath == target.imagePath )       
               &&  (this.creationDate == target.creationDate )       
               ;
    
        }
    
    
    	public static bool operator ==(Image  objA, Image  objB)
        {
            // Check if the objets are the same Image entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Image  objA, Image  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strImage = new StringBuilder();
    
    		strImage.Append("[ ");
           strImage.Append(" imageId = " + imageId + " | " );       
           strImage.Append(" likes = " + likes + " | " );       
           strImage.Append(" title = " + title + " | " );       
           strImage.Append(" description = " + description + " | " );       
           strImage.Append(" aperture = " + aperture + " | " );       
           strImage.Append(" balance = " + balance + " | " );       
           strImage.Append(" exposure = " + exposure + " | " );       
           strImage.Append(" usrId = " + usrId + " | " );       
           strImage.Append(" categoryId = " + categoryId + " | " );       
           strImage.Append(" imagePath = " + imagePath + " | " );       
           strImage.Append(" creationDate = " + creationDate + " | " );       
            strImage.Append("] ");    
    
    		return strImage.ToString();
        }
    
    
    }
}
